
#Configurations for material AstralStarmetal.
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 2107742

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"

[skyresources]
	#The rarity of this material as used in Sky Resources.
	rarity = 6
	#The default base to use in Sky Resources' condenser to create ores.
	oreBase = "minecraft:stone"
	#The item to use in Sky Resources' cauldron cleaning to dust.
	dustBase = "skyresources:techitemcomponent@0"

